{"testCaseId": "4de8035ea60fcdf87d07e0a66f2d92ca", "status": "broken", "stop": 1594454866519, "name": "test_login_2[data1]", "start": 1594454845889, "historyId": "d61d8550cf1e25dc7f3a7782fbb558ca", "statusDetails": {"trace": "self = <webtest.testcases.test_loginpytest.TestLogin object at 0x0000000004466400>, data = {'expected': '帐号或密码错误!', 'phone': '18684720553', 'pwd': 'python1'}\ninit_driver = (<selenium.webdriver.chrome.webdriver.WebDriver (session=\"0b634d13eb6591dccdd0114cb0c6d2db\")>, <webtest.pages.loginpage.LoginPage object at 0x00000000044497F0>, <webtest.pages.indexpage.IndexPage object at 0x00000000044494A8>)\n\n    @allure.story('账户、密码输入错误用例')\n    @pytest.mark.smoke\n    @pytest.mark.run(order=2)\n    @pytest.mark.usefixtures('init_driver','setup')\n    @pytest.mark.parametrize('data', data_login.incorrect_data2)\n    def test_login_2(self,data,init_driver):\n        # print(data)\n        # with allure.attach('输入用户名、密码'):\n        #     allure.attach(data)\n        driver, loginpage, indexpage = init_driver\n        loginpage.submit_login(data['phone'],data['pwd'])\n>       text=loginpage.ele_popup.text\n\nwebtest\\testcases\\test_loginpytest.py:51: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nwebtest\\pages\\loginpage.py:36: in ele_popup\n    return self.get_element_visibility(self.popup_locator)\nwebtest\\pages\\basepage.py:23: in get_element_visibility\n    raise e\nwebtest\\pages\\basepage.py:20: in get_element_visibility\n    return WebDriverWait(self.driver,timeout).until(EC.visibility_of_element_located(locator))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"0b634d13eb6591dccdd0114cb0c6d2db\")>, method = <selenium.webdriver.support.expected_conditions.visibility_of_element_located object at 0x0000000004449A20>\nmessage = ''\n\n    def until(self, method, message=''):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value is not False.\"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.time() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, 'screen', None)\n                stacktrace = getattr(exc, 'stacktrace', None)\n            time.sleep(self._poll)\n            if time.time() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message:\n\nd:\\python\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py:80: TimeoutException", "message": "selenium.common.exceptions.TimeoutException: Message:"}, "uuid": "5fe58c32-b5bc-4520-835c-30830027a8f0", "parameters": [{"name": "data", "value": "{'pwd': 'python1', 'expected': '帐号或密码错误!', 'phone': '18684720553'}"}], "fullName": "webtest.testcases.test_loginpytest.TestLogin#test_login_2", "labels": [{"name": "feature", "value": "登录用例"}, {"name": "story", "value": "账户、密码输入错误用例"}, {"name": "tag", "value": "smoke"}, {"name": "tag", "value": "@pytest.mark.usefixtures('init_driver', 'setup')"}, {"name": "tag", "value": "run(order=2)"}, {"name": "parentSuite", "value": "webtest.testcases"}, {"name": "suite", "value": "test_loginpytest"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "cnki-PC"}, {"name": "thread", "value": "841660-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "webtest.testcases.test_loginpytest"}]}